---
- name: Copy required files
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '{{ script_src }}', dest: '{{ script_dest }}' }
    - { src: '{{ service_src }}', dest: '{{ service_dest }}' }
    - { src: '{{ config_src }}', dest: '{{ config_dest }}' }

- name: Change file ownership
  file:
    path: "{{ script_dest }}{{ script_name }}"
    mode: '0744'
    
- name: Enable GitHub Watchdog
  systemd:
    name: "{{ service_name }}"
    state: started
    enabled: yes
    daemon_reload: yes

- name: Check service status
  command: systemctl status "{{ service_name }}"
